apiVersion: v1
kind: Pod
metadata:
  name: passmark-test
spec:
  containers:
  - name: passmark-test
    image: yatix/passmark-test:latest
    securityContext:
      runAsUser: 0
    volumeMounts:
    - name: output-volume
      mountPath: /output
  initContainers:
  - name: create-output-dir
    image: busybox
    command: ["/bin/sh", "-c", "mkdir -p /home/nuclab/Downloads/pt_linux_x64/PerformanceTest/passmark-result"]
    volumeMounts:
    - name: output-volume
      mountPath: /home/nuclab/Downloads/pt_linux_x64/PerformanceTest/passmark-result
  volumes:
  - name: output-volume
    hostPath:
      path: /home/nuclab/Downloads/pt_linux_x64/PerformanceTest/passmark-result
  restartPolicy: Never